version: '3.9'
services:
  host:
    build:
      context: host
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    links:
      - mf_navbar
      - mf_planet
      - mf_cards
      - mf_detalle_personaje
      - mf_detalle_planet
  mf_navbar:
    build:
      context: mf-navbar
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
  mf_planet:
    build:
      context: mf-planet
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
  mf_cards:
    build:
      context: mf-cards
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
  mf_detalle_personaje:
    build:
      context: mf-detalle-personaje
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
  mf_detalle_planet:
    build:
      context: mf-detalle-planet
      dockerfile: ./Dockerfile
    ports:
      - "8085:8085"
